name: SDK Unstable Publish

on:
  workflow_dispatch:
  push:
    branches:
      - openapi-unstable

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'jellyfin/jellyfin-sdk-typescript' }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
        with:
          ref: openapi-unstable

      - name: Set up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 16
          check-latest: true
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Update package version
        run: |
          VERSION="0.0.0-unstable.$(date +%Y%m%d%H%M)+commit.$(git rev-parse HEAD)" && \
          PACKAGE="$(jq --arg v "$VERSION" '.version = $v' package.json)" && \
          echo -E "${PACKAGE}" > package.json

      - name: Install Node.js dependencies
        run: npm ci --no-audit

      - name: Publish the SDK to npm
        run: npm publish --tag unstable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
